<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_RegressionTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>db5df642-ac5a-4996-ba77-1761d3568e0f</testSuiteGuid>
   <testCaseLink>
      <guid>342560bb-85b9-4618-9f44-ae8e830a32e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration/TC001_Create a new account successful</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46564c10-147c-414c-816e-1e2fb760cfa3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e6250b7-2806-451a-af65-783a7d2bb33c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6eed30c0-2aae-4bf0-855a-9367b02bcffa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6e104ac-6142-4e8f-ac7a-6ae805dfdec7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b17e8e54-b9c7-47a4-81c0-5b8d513b1e6e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration/TC002_Create a new account with invalid email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eb2d53c-aaae-40fa-b46f-c9139062f052</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c744f42-0bba-4c60-b810-1683e4cbfe02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ba2fb22-fb53-4668-8ecd-d076bbfde8f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e13dff1e-7263-4007-a3c3-e5d9b12bfd80</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0936ad5-92f8-494b-b438-863e0431dc9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration/TC003_Create a new account with invalid password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19a3249c-bd7d-4e69-82f4-37d1ac7ca14a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>604d7a7f-1997-4c5e-9873-3ec1dc7ccadc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cbd1a04-206c-4958-9474-045dceb9b784</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cd378736-bba7-45c8-be52-6b544bc80b6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration/TC004_Create a new account with with confirm password does not match with password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2593f582-b337-43ba-b1eb-a7ed79dfe5d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aa83628-793b-49e3-b9ed-1d7e0b96e10d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85f4c07d-b992-4bb0-972d-1be2fa064ef6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fc156be-8ac4-4f60-a45b-e3125e1f5053</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52573c77-0a62-424d-bd59-bbff9b0302ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration/TC005_Navigate to login page from registration form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>07f19880-d4fe-492f-ad6c-092a13ea5f2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration/TC006_Create a new account with empty full name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e708442-7fd2-4bf6-b923-3b017a3e900c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3f0412e-b599-4a28-99c6-694027ed7ccd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>571351b8-0bde-40e8-a331-8d7c4c588a5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac26679b-fbb4-4393-b97d-a621fda2856a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration/TC007_Create a new account with empty data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b74aa11-78a4-4439-83fe-80361a641809</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a756fe42-da1a-4865-92e2-2b862cf99dc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56b179bc-8cd3-4f06-8741-0d785fcb69ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95b5bcfd-bafb-4898-9071-02ba24fe3e45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC008_Login successful</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a9ff768-31ab-4cd4-85c2-4dbcacd9703a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebd80e58-fda0-4c1f-8b79-7eb9fe128aaf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3be242f2-ddba-4863-b741-a7840c71a0ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC009_Login with invalid email address</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d53ebc4a-2865-454b-9212-bf19d000b638</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9ab9005-2184-40dd-baf4-b160970562a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39877096-4d94-418d-aea0-f08468d4fd9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC010_Login with invalid password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3da021b-8329-4bcd-b810-04e2ae3aa5d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>258e5868-6ec6-4bc3-8070-b94661a84551</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dedd2e47-c4d8-43d5-ba0e-39c2908ff6ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC011_Login with empty data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4ed13f3f-8efa-4425-b550-3a0f98da2fa6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC012_Navigate to signup page from login form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f3f87c18-24a3-494d-ad5e-78e60964c2a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC013_Create a new story successful</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33e8e6f6-3281-430f-91c8-f3fbc90dfdf5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25f9b0c5-59e5-467a-82d3-610ba0898f4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0641b754-34d3-4e0c-93ba-f6a89fb97e29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18f0d837-1732-4e1a-824c-12247f2a0755</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC014_Create new story with empty title</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>641c9055-5415-458b-a67e-f6016d64b50a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>458eb2fc-487d-4fca-b4e5-1473760db431</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6cdfff8a-c2e0-48a5-a19b-99262942bef4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC015_Create new story with empty label</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91b2a4dc-d0de-44fa-9ea6-9ec07e5513c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2136633-7d24-41c9-af89-a422a7513198</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7dad0ba3-b43c-49e7-b0b6-834040b8fe50</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC016_Create new story with empty priority</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cdf7271-8e4e-4571-a0a0-a8a65f6ed355</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31625007-9e88-4358-8a7e-847b4a055c6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38c92e30-513a-4955-a587-042da5119424</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8a4054f-9933-495c-8fa4-42691a4d6ef1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC017_Create new story with empty assigned to</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad16142d-9f10-48e3-a625-5f7615740026</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74e0641d-4148-405a-89a7-d8286e1eaa30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e7bc9b9-0f6c-40e9-8123-198de7bc20d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08a57a21-d817-4d06-8f6b-241433c3768d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC018_Create new story with empty story status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>413002df-bb1d-4ec0-9208-25bd8cbebb87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14afe63d-83c6-407c-9038-d5eaadcca833</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be8d628c-c1bf-4e68-90f8-b1c5e2ddc542</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42acedae-e1f0-4e39-9e56-1e9dd716abe4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC019_Create new story with empty description</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6f1ea35-ce53-4821-9a24-95440ff7cb60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ddfa5f6-eb1c-4768-a06f-78980297ed52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87b816bf-1937-4112-94e9-7423b3ab16c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea957bb7-ec93-447c-be15-88379f02de70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC020_Cancel to create new story</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7483d07a-d75f-4e2d-b93c-bf91aebd3e66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>924d15c8-fb4c-440e-bdd5-323d3c08c40b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eeeee4e0-cc1d-4908-88c2-9256e4fd8630</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b800b481-edbe-422a-83b6-0487bfac7344</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC021_Update the existing story successful</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9be1a581-a899-43c9-b20e-859218cdd05f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60ccb85d-004b-49ad-8214-b2123533d6cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC022_View the existing story</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45c35d06-dc72-48cc-a0bd-23702a8411c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9331f36-68a6-4366-83be-e355576b3396</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC024_Cancel to delete the existing story</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>051ae198-da93-4853-8409-a19a7abfb0ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC023_Delete the existing story successful</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>cc082856-6e07-431e-9e79-c5c4d3464a33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC025_Inquiry story with valid data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e482024-db8f-431f-90be-b6257bcc8521</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>312e77f4-c073-4217-ae41-b6922d48eaf5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Story/TC026_Inquiry story with invalid data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebeea24a-64f3-4718-82d3-4ac675c8c394</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
