<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_points</name>
   <tag></tag>
   <elementGuidId>94e07f05-a155-4352-9e57-e75fd01a09ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#story_point_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='story_point_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Story Points&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53443242-e1d7-424e-92f5-cf60d5a97eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-center input-quantity input-spin-none</value>
      <webElementGuid>56f6b111-41ba-4d9d-8585-e41e8f4ff182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5dd7aaff-2b73-4a2c-a2bc-8f41fa275493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>74379e23-1323-4d47-a19d-7d1ac4097afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e419132a-d444-4821-850a-1af401204645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>story_point_id</value>
      <webElementGuid>f90531dc-f5ff-4541-8e89-d236aa19529f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>points</value>
      <webElementGuid>882b0628-f84f-4e79-9981-3d76a7c9cb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;story_point_id&quot;)</value>
      <webElementGuid>8dee0a71-628b-4766-a422-090fa6e781e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='story_point_id']</value>
      <webElementGuid>26642f74-cda8-487b-8e65-a4fc0e121ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='top']/div/div/div/div/div/div/div[2]/form/div[6]/div/input</value>
      <webElementGuid>263b28bc-a7a6-40d2-a548-a3162be135d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>52aa2c6f-a70b-4213-a515-3d44b7a973ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'story_point_id' and @name = 'points']</value>
      <webElementGuid>f2fa3b0e-a4de-4f41-8c51-95269c8d772a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
