<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Story Label_label</name>
   <tag></tag>
   <elementGuidId>e3f7d488-d625-4e6f-8f11-333868d38805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter story label...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd799b9d-d223-4446-bd07-4c823b95d4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ef11a3fd-4767-4072-91ec-d578ca45c835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0c67f8d1-4ff7-442b-926c-cc5044bdc022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter story label...</value>
      <webElementGuid>a350d3a8-daf2-4240-aea3-63360905080d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0b4bb613-1f0c-430e-810b-972959991811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64f7260d-adfc-4b68-8901-6f0c150e127c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label&quot;)</value>
      <webElementGuid>364ada7c-1ef0-41fe-a96b-44084f752707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='label']</value>
      <webElementGuid>2c816724-7109-4517-82ce-c71c7699e361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='top']/div/div/div/div/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>54f17409-a52e-4dfa-9461-20b3ce77e27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>828383e7-e0a0-463e-a666-ca7e63ac3d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'label' and @placeholder = 'Enter story label...' and @name = 'label' and @type = 'text']</value>
      <webElementGuid>9be3d6b4-448b-4dcf-8b0c-0c4f8abdb63a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
