<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select priority.                    _6b5064</name>
   <tag></tag>
   <elementGuidId>0f9ebf9d-2d3d-447e-93bd-7c105b327334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#priority_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='priority_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Priority&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5720965c-a6e4-4424-a3a3-f5c53e9369e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1a84c0cc-bbac-4364-a3f3-ba2a3178e62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>priority</value>
      <webElementGuid>6e017573-8f79-4b0b-871b-76cfe71180b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>priority_id</value>
      <webElementGuid>2d44fbd9-b19f-4ed5-a647-fcbd3d44bcfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Select priority...
                                                        Low
                                                        Medium
                                                        High
                                                    </value>
      <webElementGuid>57ce1349-2fa6-4fa4-98a7-d31c32e1a372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;priority_id&quot;)</value>
      <webElementGuid>51d8401c-1fae-44bc-ac20-6b5c5a71efb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='priority_id']</value>
      <webElementGuid>6b73fefa-116e-48f8-ac2b-3f9fcc4c9b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='top']/div/div/div/div/div/div/div[2]/form/div[3]/select</value>
      <webElementGuid>f7156fb2-8135-45bf-9b94-7d7092f40f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[1]/following::select[1]</value>
      <webElementGuid>3ac37c80-26d0-4f13-9e75-e73f57f9b44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Story Label'])[1]/following::select[1]</value>
      <webElementGuid>3157500e-dd38-4b3b-be9b-d6565e47fe20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign To'])[1]/preceding::select[1]</value>
      <webElementGuid>6cee3a49-e664-4f0b-a4bc-e37fa2961caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Story Status'])[1]/preceding::select[2]</value>
      <webElementGuid>14b4f9d9-199d-4643-8c84-4cb44ed2e759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a5a055dc-65a5-4eeb-8b09-6c451facb7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'priority' and @id = 'priority_id' and (text() = '
                            Select priority...
                                                        Low
                                                        Medium
                                                        High
                                                    ' or . = '
                            Select priority...
                                                        Low
                                                        Medium
                                                        High
                                                    ')]</value>
      <webElementGuid>cab263e8-e100-41bc-a59e-bbe309b70a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
