<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_description</name>
   <tag></tag>
   <elementGuidId>f1853bc9-175e-46cd-85fd-43c87771f2d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#description_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='description_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter story description here...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2fbcf3f8-ed72-4b03-a0b2-ad59020fbffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>08e13c27-2c4d-4c21-bb3f-208256791629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter story description here...</value>
      <webElementGuid>48e18748-6d72-45ca-90d0-090c4fe4a955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description_id</value>
      <webElementGuid>bb1eded1-a01e-4754-8d1e-0400d34605a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>045bfac1-9ed6-4785-9bc1-b340334e5076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>f6ad25af-c907-459e-bac8-7ab9294cb121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>e0f18e6d-a015-4d95-aac1-177d62c7d2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description_id&quot;)</value>
      <webElementGuid>576bd93f-94a7-4aaf-ab9b-f7cf06689817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='description_id']</value>
      <webElementGuid>1909ed6a-6a39-4860-bafb-51af0ac8bc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='top']/div/div/div/div/div/div/div[2]/form/div[7]/textarea</value>
      <webElementGuid>ca72390f-ce13-4d45-b867-7a59d6bc7011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4a53ca85-c19e-4deb-ba90-a10bfdc82756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Enter story description here...' and @id = 'description_id' and @name = 'description']</value>
      <webElementGuid>097a9a85-0d16-4ac1-8c95-afb6cd10bee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
